{% set name = "llama-cloud" %}
{% set version = "0.1.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_cloud-{{ version }}.tar.gz
  sha256: 200349d5d57424d7461f304cdb1355a58eea3e6ca1e6b0d75c66b2e937216983

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - pydantic >=1.10
    - httpx >=0.20.0
    - certifi >=2024.7.4

test:
  imports:
    - llama_cloud
    - llama_cloud.client
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://cloud.llamaindex.ai
  summary: Turn your enterprise data into production-ready LLM applications
  description: |
    llama-cloud is the Python client for LlamaCloud, providing APIs for
    building production-ready LLM applications.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/run-llama/llama_cloud
  doc_url: https://docs.cloud.llamaindex.ai

extra:
  recipe-maintainers:
    - jan-janssen
